kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: kafka-zookeeper-regional
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  type: pd-ssd
  replication-type: regional-pd
  zones: us-central1-a, us-central1-c
